Repository imprint-serde/imprint, pull requests merged in 2025-05, with the labels that each got.

#6 add implementation for projection
  README.md
  src/lib.rs
  src/ops.rs
  src/types.rs
Labels: size:L

#7 implementation for record merge/joins
  src/lib.rs
  src/ops.rs
Labels: size:L

#12 update README with benchmark and images
  .github/images/imprint-logo.png
  .github/images/imprint-merge_bench.png
  README.md
Labels: documentation, size:S

#13 add LICENSE file (MIT)
  LICENSE
Labels: size:XS

#16 add projection benchmarks
  .github/images/imprint-project_bench.png
  README.md
  benches/proto/test_record.proto
  benches/src/serialization.rs
  benches/src/types.rs
  src/ops.rs
Labels: documentation, enhancement, size:L

#23 fix: support 0-len arrays and nested records
  Cargo.toml
  README.md
  proptest-regressions/serde.txt
  src/ops.rs
  src/serde.rs
  src/types.rs
  src/writer.rs
Labels: bug, size:L

#21 Add map type
  README.md
  src/serde.rs
  src/types.rs
Labels: enhancement, size:L, lgtm

#24 Add FORMAT.md
  FORMAT.md
  README.md
  src/serde.rs
Labels: documentation, size:L, lgtm

#27 fix: ensure that payload has a deterministic order
  .gitignore
  Cargo.lock
  Cargo.toml
  src/lib.rs
  src/ops.rs
Labels: bug, size:L, lgtm

#32 add benchmark to CI/CD
  .github/workflows/bench.yml
  scripts/ci_bench.sh
Labels: enhancement, size:L
